name: rdkit
channels:
  - conda-forge
  - rdkit
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=2.1.4
#  - rdkit=2024.09.1
  - rdkit=2023.09.6
  - libboost=1.84.0
  - libboost-python=1.84.0
  - libboost-headers=1.84.0
  - cython=3.0.11

  - tqdm
  - zstandard

